/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlMetha;
import controlador.CtrlWeed;
import javax.swing.JOptionPane;
import modelo.ConsultasMetha;
import modelo.ConsultasWeed;
import modelo.Methamphetamine;
import modelo.Weed;

/**
 *
 * @author fabia
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú DrugStore");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        weedMenuItem = new javax.swing.JMenuItem();
        methaMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        informeWeedMenuItem = new javax.swing.JMenuItem();
        informeMethaMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        estadisticaWeedMenuItem = new javax.swing.JMenuItem();
        cantidadMethaMenuItem1 = new javax.swing.JMenuItem();
        cantidadMaxGrWeedMenuItem = new javax.swing.JMenuItem();
        cantMaxGrMethaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(550, 444));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Agregar");

        weedMenuItem.setText("Weed");
        weedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weedMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(weedMenuItem);

        methaMenuItem2.setText("Methamphetamine");
        methaMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methaMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(methaMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informe");

        informeWeedMenuItem.setText("Generar informe weed");
        informeWeedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeWeedMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(informeWeedMenuItem);

        informeMethaMenuItem.setText("Generar informe methamphetamina");
        informeMethaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeMethaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(informeMethaMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estadisticas");

        estadisticaWeedMenuItem.setText("Cantidad de registros weed");
        estadisticaWeedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticaWeedMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(estadisticaWeedMenuItem);

        cantidadMethaMenuItem1.setText("Cantidad de registros metha");
        cantidadMethaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMethaMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(cantidadMethaMenuItem1);

        cantidadMaxGrWeedMenuItem.setText("Cantidad maxima de gramos weed");
        cantidadMaxGrWeedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMaxGrWeedMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cantidadMaxGrWeedMenuItem);

        cantMaxGrMethaMenuItem.setText("Cantidad maxima de gramos metha");
        cantMaxGrMethaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantMaxGrMethaMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cantMaxGrMethaMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weedMenuItemActionPerformed
        Weed mod = new Weed();
        ConsultasWeed modC = new ConsultasWeed();
        frmWeed frm = new frmWeed();
        CtrlWeed ctrl = new CtrlWeed(mod, modC, frm);
        
        ctrl.iniciarWeed();
        frm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_weedMenuItemActionPerformed

    private void methaMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methaMenuItem2ActionPerformed
        Methamphetamine mod2 = new Methamphetamine();
        ConsultasMetha modC2 = new ConsultasMetha();
        frmMetha frm2 = new frmMetha();
        CtrlMetha ctrl2 = new CtrlMetha(mod2, modC2, frm2);
        
        ctrl2.iniciarMetha();
        frm2.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_methaMenuItem2ActionPerformed

    private void informeWeedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeWeedMenuItemActionPerformed
        frmInformeWeed informe = new frmInformeWeed();
        informe.setVisible(true);
        dispose();
    }//GEN-LAST:event_informeWeedMenuItemActionPerformed

    private void informeMethaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeMethaMenuItemActionPerformed
        frmInformeMetha informe = new frmInformeMetha();
        informe.setVisible(true);
        dispose();
    }//GEN-LAST:event_informeMethaMenuItemActionPerformed

    private void estadisticaWeedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticaWeedMenuItemActionPerformed

        ConsultasWeed consulta = new ConsultasWeed();
        JOptionPane.showMessageDialog(null,"Hay "+consulta.contWeed()+" Registros de Weed en la base de datos.");
        
    }//GEN-LAST:event_estadisticaWeedMenuItemActionPerformed

    private void cantidadMethaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMethaMenuItem1ActionPerformed
        
        ConsultasMetha consulta = new ConsultasMetha();
        JOptionPane.showMessageDialog(null, "Hay "+consulta.contMetha()+" Registros de Weed en la base de datos");
        
    }//GEN-LAST:event_cantidadMethaMenuItem1ActionPerformed

    private void cantMaxGrMethaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantMaxGrMethaMenuItemActionPerformed
        
        ConsultasMetha consulta = new ConsultasMetha();
        JOptionPane.showMessageDialog(null, "La cantidad mas alta de gramos metha es "+consulta.maxMetha()+" GR.");
        
    }//GEN-LAST:event_cantMaxGrMethaMenuItemActionPerformed

    private void cantidadMaxGrWeedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMaxGrWeedMenuItemActionPerformed
        
        ConsultasWeed consulta = new ConsultasWeed();
        JOptionPane.showMessageDialog(null,"La cantidad mas alta de gramos weed es "+consulta.maxWeed()+" GR.");
        
    }//GEN-LAST:event_cantidadMaxGrWeedMenuItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cantMaxGrMethaMenuItem;
    private javax.swing.JMenuItem cantidadMaxGrWeedMenuItem;
    private javax.swing.JMenuItem cantidadMethaMenuItem1;
    private javax.swing.JMenuItem estadisticaWeedMenuItem;
    private javax.swing.JMenuItem informeMethaMenuItem;
    private javax.swing.JMenuItem informeWeedMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem methaMenuItem2;
    private javax.swing.JMenuItem weedMenuItem;
    // End of variables declaration//GEN-END:variables
}
